version: "3.9"

services:
    fin_apiDB:
        image: postgres
        container_name: fin_apiDB
        restart: always
        ports:
        - 5432:5432
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=fin_api
        volumes:
        - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local
